server:
  port: 6789

spring:
  thymeleaf:
    encoding: UTF-8
    cache: false  #由于thymeleaf页面会缓存数据，如果使用它默认缓存，可能会导致新数据无法正常显示
    mode: LEGACYHTML5 #不启用html5的较验规则,不会检测是否有结束标记
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oa?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 10MB #上传的单个文件大小，不能超过1MB
      max-request-size: 100MB #上传的单个文件大小，不能超过1MB
  activiti:
    check-process-definitions: false #不去检查工程是否包含bpmn文件
    database-schema: true  #如果数据表已存在就继续使用，不存在就创建

mybatis:
  type-aliases-package: org.java.entity
  mapper-locations: mapper/*Mapper.xml

#定义变量，用于保存文件上传的目录
file:
  processDefinitionKey: myProcess

##以debug方式，显示org.java.dao包所有的底层sql语句
logging:
  level:
    org:
      java:
        dao: debug
